import { Habit, PeriodicityUnit as PU } from "./types";

export const habits: Habit[] = [
  {
    id: "dayPlanning",
    label: "Planning my day",
    cue: "After breakfast",
    reward: "More productive and organized day",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "exercise",
    label: "Exercise",
    cue: "Any suitable time during the day",
    reward: "Better health, more energy, and improved mood",
    targetCount: 5,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Week,
    active: true,
    permanent: true,
  },
  {
    id: "morningWarmUp",
    label: "Morning Physical Warm-Up",
    cue: "After waking up",
    reward: "Increased energy and readiness for the day",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "recreation",
    label: "Having fun",
    cue: "In the evening or during free time",
    reward: "Relaxation, joy, and stress relief",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "selfPleasure",
    label: "FPF",
    cue: "At free from work personal time",
    reward: "Better focus and increasing ability to feel joy",
    targetCount: 7,
    periodicityMultiplier: 10,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "poetryEngaging",
    label: "Spend time with poetry",
    cue: "At leisure time",
    reward:
      "Happiness and healthy feelings expression from engaging with poetry",
    targetCount: 3,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Month,
    active: true,
  },
  {
    id: "programmingLearning",
    label: "Programming study",
    cue: "Dedicated learning time",
    reward: "Skill development, career growth, and problem-solving mastery",
    targetCount: 3,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Week,
    active: true,
  },
  {
    id: "recreationalCannabis",
    label: "Getting high",
    cue: "Day off (if next day is also day off, then) in safe calm well prepared environment and mood",
    reward: "Self-care routine, relaxation, stress relief",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Week,
    active: true,
    maxLimit: {
      count: 20,
      periodicityMultiplier: 6,
      periodicityUnit: PU.Month,
    },
  },
] as const;
