import { Habit, PeriodicityUnit as PU } from "./types";

export const habits: Habit[] = [
  {
    id: "dayPlanning",
    label: "Planning my day",
    cue: "After breakfast",
    reward: "More productive and organized day",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "exercise",
    label: "Exercise",
    cue: "Any suitable time during the day",
    reward: "Better health, more energy, and improved mood",
    targetCount: 5,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Week,
    active: true,
    permanent: true,
  },
  {
    id: "morningPhysicalWarmUp",
    label: "Morning Physical Warm-Up",
    cue: "After waking up",
    reward: "Increased energy and readiness for the day",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "havingFun",
    label: "Having fun",
    cue: "In the evening or during free time",
    reward: "Relaxation, joy, and stress relief",
    targetCount: 1,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "fpf",
    label: "FPF",
    cue: "At free from work personal time",
    reward: "Better focus and increasing ability to feel joy",
    targetCount: 7,
    periodicityMultiplier: 10,
    periodicityUnit: PU.Day,
    active: true,
  },
  {
    id: "poetry",
    label: "Spend time with poetry",
    cue: "At leisure time",
    reward:
      "Happiness and healthy feelings expression from engaging with poetry",
    targetCount: 3,
    periodicityMultiplier: 1,
    periodicityUnit: PU.Month,
    active: true,
  },
] as const;
